# Generated by Django 5.2.15 on 2026-09-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='redosled')),
                ('is_published', models.BooleanField(default=True, verbose_name='objavljeno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'projekat',
                'verbose_name_plural': 'projekti',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='slika')),
                ('is_main', models.BooleanField(default=False, verbose_name='glavna slika')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='redosled')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.project', verbose_name='projekat')),
            ],
            options={
                'verbose_name': 'slika projekta',
                'verbose_name_plural': 'slike projekata',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('sr-latn', 'Srpski'), ('en', 'English')], max_length=10, verbose_name='jezik')),
                ('title', models.CharField(max_length=255, verbose_name='naziv')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='opis')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='website.project', verbose_name='projekat')),
            ],
            options={
                'verbose_name': 'prevod projekta',
                'verbose_name_plural': 'prevodi projekata',
                'constraints': [models.UniqueConstraint(fields=('project', 'language'), name='unique_project_language')],
            },
        ),
    ]
