# Generated by Django 5.2.15 on 2026-09-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttranslation',
            name='status',
            field=models.CharField(choices=[('source', 'Izvorni jezik'), ('draft', 'Nacrt'), ('pending', 'Na odobrenju'), ('approved', 'Odobreno'), ('rejected', 'Odbačeno')], default='draft', max_length=20, verbose_name='status prevoda'),
        ),
    ]
